name: Build

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install dependencies
      run: |
        go get -v -d ./...

    - name: Build
      run: |
        go build -v -o infer ./cmd/infer
    
    - name: Run unit tests
      run: |
        go test -v ./...

    - name: Run infer tests
      run: |
        ./infer -v

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: infer
        path: infer
